language: shell
script:
  - cd $TRAVIS_BUILD_DIR
  - cd ..
  - mv $TRAVIS_BUILD_DIR ~/.emacs.d
  - cd ~/.emacs.d
  - emacs --version
  - make
  - emacs -l ~/.emacs.d/init.el -batch --eval='(message "Working")'
