(source "elpa" "http://tromey.com/elpa/")
(source "marmalade" "http://marmalade-repo.org/s/")
 
(package "magit")
;; (package "helm")
(package "ace-jump-mode")
(package "clojure-mode")
(package "elisp-slime-nav")
(package "expand-region")
(package "highlight-parentheses")
(package "ido-ubiquitous")
(package "igrep")
(package "js2-mode")
(package "maxframe")
(package "mo-git-blame")
(package "multi-term")
(package "paredit")
(package "real-auto-save")
(package "smex")
(package "undo-tree")
(package "yasnippet")
(package "markdown-mode")
;; (package "nrepl")
(package "multiple-cursors")
