(source "elpa" "http://tromey.com/elpa/")
(source "marmalade" "http://marmalade-repo.org/packages/")
 
(package "magit")
(package "ace-jump-mode")
(package "anything")
(package "anything-complete")
(package "anything-config")
(package "anything-match-plugin")
(package "anything-obsolete")
(package "clojure-mode")
(package "elisp-slime-nav")
(package "expand-region")
(package "highlight-parentheses")
(package "ido-ubiquitous")
(package "igrep")
(package "js2-mode")
(package "mark-more-like-this")
(package "mark-multiple")
(package "maxframe")
(package "mo-git-blame")
(package "multi-term")
(package "paredit")
(package "real-auto-save")
(package "smex")
(package "undo-tree")
(package "yasnippet")
(package "markdown-mode")
(package "nrepl")
